import React, { useState, useEffect, useMemo } from 'react';
import {
  X,
  Sparkles,
  Play,
  RotateCcw,
  Copy,
  Check,
  Save,
  Code2,
  Eye,
  ExternalLink,
  Layers,
  Wand2,
  AlertCircle,
  Maximize2
} from 'lucide-react';
import { ReferenceItem, Cassette } from '../types';
import { generatePageFromReference } from '../utils/gemini';
import { buildSandboxedHtml } from '../utils/runner';

interface GenerateLandingModalProps {
  reference: ReferenceItem;
  isOpen: boolean;
  onClose: () => void;
  onSaveToGallery: (newCassette: Cassette) => void;
}

const PROMPT_SUGGESTIONS = [
  'Создай интерактивный лендинг дизайн-студии с акцентом на кинетическую типографику и неоновые акценты из референса',
  'Создай футуристичный HUD-дашборд с полупрозрачными стеклянными карточками, графиками и анимацией',
  'Сделай минималистичный промо-сайт выставки цифрового искусства с темной темой и анимированным Hero-блоком',
  'Создай портфолио креативного разработчика с интерактивными hover-эффектами и галереей кейсов'
];

export const GenerateLandingModal: React.FC<GenerateLandingModalProps> = ({
  reference,
  isOpen,
  onClose,
  onSaveToGallery
}) => {
  const [prompt, setPrompt] = useState(
    `Создай интерактивный промо-лендинг, гармонично воплощающий визуальный стиль, шрифтовую сетку и цветовую палитру из референса «${reference.title}».`
  );
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState<string>('');
  const [errorMsg, setErrorMsg] = useState<string>('');
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');
  const [copied, setCopied] = useState(false);
  const [cassetteTitle, setCassetteTitle] = useState(`${reference.title} // Landing`);
  const [saveSuccess, setSaveSuccess] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setCassetteTitle(`${reference.title} // Landing`);
      setSaveSuccess(false);
    }
  }, [isOpen, reference]);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    setIsGenerating(true);
    setErrorMsg('');
    setSaveSuccess(false);

    const res = await generatePageFromReference({
      prompt,
      refTitle: reference.title,
      refComments: reference.comments || [],
      refImageBase64: reference.image.startsWith('data:') ? reference.image : undefined
    });

    setIsGenerating(false);

    if (res.success && res.html) {
      setGeneratedHtml(res.html);
      setActiveTab('preview');
    } else {
      setErrorMsg(res.error || 'Failed to generate page. Please check Gemini API connection.');
    }
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSave = () => {
    if (!generatedHtml) return;

    const newId = `gen-landing-${Date.now().toString(36)}`;
    const newCassette: Cassette = {
      manifest: {
        id: newId,
        title: cassetteTitle.trim() || `${reference.title} Page`,
        type: 'html',
        description: `Landing page generated by Gemini AI from reference «${reference.title}». Prompt: ${prompt.slice(0, 120)}...`,
        tags: Array.from(new Set([...reference.tags, 'gemini-ai', 'landing', 'moodboard-gen'])),
        groups: reference.groups || ['Структура', 'Цвета', 'Шрифты'],
        comments: [
          `Сгенерировано по референсу: ${reference.title}`,
          `Промпт: ${prompt}`
        ],
        created: new Date().toISOString().split('T')[0],
        author: 'Gemini AI'
      },
      code: generatedHtml,
      isCustom: true
    };

    onSaveToGallery(newCassette);
    setSaveSuccess(true);
    setTimeout(() => {
      onClose();
    }, 1200);
  };

  const sandboxedSrcDoc = buildSandboxedHtml('html', generatedHtml);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-2 sm:p-4 md:p-6 animate-fade-in">
      <div className="w-full h-full max-w-6xl bg-[#0d0f14] border border-slate-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="px-5 py-3.5 bg-[#12151d] border-b border-slate-800 flex items-center justify-between flex-shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-gradient-to-tr from-violet-600 to-pink-600 text-white shadow-md shadow-violet-600/30">
              <Wand2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                Generate Landing from Reference
                <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-violet-950/80 border border-violet-700/60 text-violet-300">
                  Gemini 3.7 Flash
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Visual source: <span className="text-slate-200 font-semibold">{reference.title}</span>
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Main Body */}
        <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
          {/* Left / Config Panel */}
          <div className="w-full lg:w-[380px] bg-[#0f121a] border-b lg:border-b-0 lg:border-r border-slate-800 p-4 overflow-y-auto space-y-4 flex-shrink-0">
            {/* Reference Mini Card */}
            <div className="p-3 bg-slate-900/90 border border-slate-800 rounded-xl flex gap-3 items-center">
              <div className="w-16 h-16 rounded-lg bg-slate-950 overflow-hidden border border-slate-800 flex-shrink-0 flex items-center justify-center">
                <img
                  src={reference.image}
                  alt={reference.title}
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="min-w-0 flex-1">
                <h4 className="text-xs font-bold text-white truncate">{reference.title}</h4>
                <div className="flex flex-wrap gap-1 mt-1">
                  {reference.tags.slice(0, 3).map((t) => (
                    <span
                      key={t}
                      className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-slate-800 text-violet-300"
                    >
                      #{t}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Prompt Input */}
            <div>
              <label className="text-xs font-semibold text-slate-200 block mb-1">
                Опиши, что сгенерировать:
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={4}
                placeholder="Опиши желаемый сайт, секции, стилистику и интерактивные элементы..."
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700/80 rounded-xl text-white focus:outline-none focus:border-violet-500 text-xs resize-none"
              />
            </div>

            {/* Prompt Suggestions */}
            <div>
              <span className="text-[11px] font-medium text-slate-400 block mb-1.5">
                Быстрые идеи промптов:
              </span>
              <div className="space-y-1.5">
                {PROMPT_SUGGESTIONS.map((sug, i) => (
                  <button
                    key={i}
                    onClick={() => setPrompt(sug)}
                    className="w-full text-left p-2 rounded-lg bg-slate-900/60 hover:bg-slate-800 border border-slate-800/80 hover:border-slate-700 text-[11px] text-slate-300 hover:text-white transition-colors"
                  >
                    ✨ {sug}
                  </button>
                ))}
              </div>
            </div>

            {/* Generate Action Button */}
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !prompt.trim()}
              className="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-violet-600 via-pink-600 to-amber-500 hover:from-violet-500 hover:to-pink-500 text-white text-xs font-bold shadow-lg shadow-violet-600/30 transition-all flex items-center justify-center gap-2 active:scale-98 disabled:opacity-50"
            >
              <Sparkles className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
              <span>{isGenerating ? 'Gemini AI is generating website...' : '✨ Generate Landing Page'}</span>
            </button>

            {errorMsg && (
              <div className="p-2.5 rounded-xl bg-rose-950/40 border border-rose-800 text-rose-300 text-xs flex items-start gap-2">
                <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5 text-rose-400" />
                <span>{errorMsg}</span>
              </div>
            )}
          </div>

          {/* Right / Live Preview & Code Inspector */}
          <div className="flex-1 flex flex-col bg-[#0a0c10] overflow-hidden min-h-[300px]">
            {/* Top Toolbar */}
            <div className="px-4 py-2 bg-[#12151d] border-b border-slate-800 flex items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <div className="flex items-center bg-slate-900 border border-slate-800 rounded-lg p-0.5">
                  <button
                    onClick={() => setActiveTab('preview')}
                    className={`px-3 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${
                      activeTab === 'preview'
                        ? 'bg-violet-600 text-white shadow-sm'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <Eye className="w-3.5 h-3.5" />
                    <span>Live Preview</span>
                  </button>
                  <button
                    onClick={() => setActiveTab('code')}
                    className={`px-3 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${
                      activeTab === 'code'
                        ? 'bg-violet-600 text-white shadow-sm'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <Code2 className="w-3.5 h-3.5" />
                    <span>HTML/CSS Code</span>
                  </button>
                </div>
              </div>

              {generatedHtml && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopyCode}
                    className="px-2.5 py-1 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 text-xs font-medium transition-colors flex items-center gap-1"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                </div>
              )}
            </div>

            {/* Content Display */}
            <div className="flex-1 relative overflow-hidden bg-[#06080c]">
              {!generatedHtml && !isGenerating && (
                <div className="h-full flex flex-col items-center justify-center p-8 text-center text-slate-500 space-y-3">
                  <div className="w-14 h-14 rounded-2xl bg-slate-900/80 border border-slate-800 flex items-center justify-center text-violet-400">
                    <Wand2 className="w-7 h-7 stroke-1" />
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-slate-300">Ready to synthesize</h3>
                    <p className="text-xs text-slate-500 max-w-sm mt-1">
                      Click «✨ Generate Landing Page» on the left to create a full-featured website inspired by this moodboard reference.
                    </p>
                  </div>
                </div>
              )}

              {isGenerating && (
                <div className="h-full flex flex-col items-center justify-center p-8 text-center space-y-4">
                  <div className="w-16 h-16 rounded-full border-4 border-violet-500/20 border-t-violet-500 animate-spin flex items-center justify-center">
                    <Sparkles className="w-6 h-6 text-violet-400 animate-pulse" />
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-white">Synthesizing Creative Landing Page...</h3>
                    <p className="text-xs text-slate-400 mt-1">
                      Gemini is generating responsive layouts, typography hierarchy, and interactive scripts.
                    </p>
                  </div>
                </div>
              )}

              {generatedHtml && !isGenerating && activeTab === 'preview' && (
                <iframe
                  title="Generated Landing Preview"
                  srcDoc={sandboxedSrcDoc}
                  sandbox="allow-scripts allow-same-origin"
                  className="w-full h-full border-0 bg-white"
                />
              )}

              {generatedHtml && !isGenerating && activeTab === 'code' && (
                <textarea
                  value={generatedHtml}
                  onChange={(e) => setGeneratedHtml(e.target.value)}
                  className="w-full h-full p-4 bg-[#0a0c10] text-emerald-300 font-mono text-xs focus:outline-none resize-none selection:bg-violet-600 selection:text-white"
                  spellCheck={false}
                />
              )}
            </div>

            {/* Bottom Save Bar */}
            {generatedHtml && (
              <div className="p-3 bg-[#12151d] border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2 flex-1 min-w-[200px]">
                  <input
                    type="text"
                    value={cassetteTitle}
                    onChange={(e) => setCassetteTitle(e.target.value)}
                    placeholder="Cassette Title"
                    className="px-3 py-1.5 bg-slate-900 border border-slate-700 rounded-lg text-white text-xs font-medium w-full max-w-xs focus:border-violet-500 focus:outline-none"
                  />
                </div>

                <button
                  onClick={handleSave}
                  className="px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold shadow-md shadow-emerald-600/30 transition-all flex items-center gap-1.5 active:scale-95"
                >
                  {saveSuccess ? (
                    <>
                      <Check className="w-4 h-4" />
                      <span>Saved to Gallery!</span>
                    </>
                  ) : (
                    <>
                      <Save className="w-4 h-4" />
                      <span>Save to Gallery</span>
                    </>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
